name: cerise
description: A cross-platform application, provides images and videos bed with GitHub repository and userful gadgets, powered by Flutter.
publish_to: 'none'
version: 1.6.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: 1.0.4
  dart_vlc: 0.1.8
  desktop_webview_window: 0.1.3
  device_preview: 0.7.5
  extended_nested_scroll_view: 5.0.0
  json2yaml: 3.0.0
  fijkplayer: 0.10.0
  file_selector: 0.8.2+1
  file_selector_platform_interface: 2.0.2
  file_selector_windows: 0.0.2+1
  flutter_easyloading: 3.0.3
  flutter_local_notifications: 9.1.4
  flutter_markdown: 0.6.8
  get: 4.5.1
  github:
    git:
      url: https://github.com/ggdream/github.dart
      ref: 260cf769e0f3435773a5291fe82d1f9201b97836
  gesture_password_widget: 2.0.0
  image_picker: 0.8.4+4
  oauth2: 2.0.0
  oktoast: 3.1.5
  path: 1.8.0
  path_provider: 2.0.7
  permission_handler: 8.3.0
  photo_view: 0.13.0
  qr_flutter: 4.0.0
  scan: 1.5.0
  screenshot: 1.2.3
  shared_preferences: 2.0.9
  share_plus: 3.0.4
  system_tray: 0.0.7
  timeago: 3.1.0
  url_launcher: 6.0.16
  video_player: 2.2.7
  wakelock: 0.5.6
  waterfall_flow: 3.0.1
  webview_flutter: 2.3.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753
      path: plugins/window_size
  yaml: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  get_cli: 1.6.0
  flutter_native_splash: 1.3.2
  flutter_launcher_icons: 0.9.2
  msix: 2.6.4
  pub_version_plus: 1.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: Girl
      fonts:
        - asset: assets/fonts/girl.ttf
  assets:
    - assets/raw/
    - assets/icons/
    - assets/data/json/
    - assets/data/text/
    - assets/images/
    - assets/images/login/
    - assets/images/scan/

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/raw/logo.png'
  fullscreen: true

flutter_icons:
  image_path: 'assets/raw/logo.png'
  android: true
  ios: true
  remove_alpha_ios: true