name: cerise
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: 1.0.2
  dart_vlc: 0.1.8
  device_preview: 0.7.4
  fijkplayer: 0.10.0
  get: 4.3.8
  github: 8.2.3
  gesture_password_widget: 2.0.0
  permission_handler: 8.2.5
  photo_view: 0.13.0
  shared_preferences: 2.0.8
  url_launcher: 6.0.12
  video_player: 2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0
  get_cli: 1.6.0
  flutter_native_splash: 1.2.4
  flutter_launcher_icons: 0.9.2


flutter:
  uses-material-design: true


flutter_native_splash:
  color: '#ffffff'
  image: 'assets/raw/logo.png'
  fullscreen: true

flutter_icons:
  image_path: 'assets/raw/logo.png'
  android: true
  ios: true
  remove_alpha_ios: true
