name: build windows

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows -v
      - run: sudo apt-get update && sudo apt-get install -y zip
      - run: zip -r build/windows/runner/cerise-${{ github.ref }}-win-x64.zip build/windows/runner/Release
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/windows/runner/cerise-${{ github.ref }}-win-x64.zip
          asset_name: cerise-${{ github.ref }}-win-x64.zip
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: false
